version: "3.9"
services:
  potatoescan:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEMO_MODE=0
      - MODEL_DIR=/app/models
      - OUTPUTS_DIR=/app/outputs
      - UPLOADS_DIR=/app/uploads
      - ALLOWED_ORIGINS=*
      - MODEL_CONF=0.25
      - MODEL_IMGSZ=640
      - FRAME_MAX_EDGE=640
      - VIDEO_SAMPLE_FPS=5
      - STREAM_INFERENCE_FPS=2
      - STREAM_ALLOWED_SCHEMES=rtmp,rtsp,http,https
      - STREAM_ALLOWED_HOSTS=mediamtx,159.89.28.191
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - mediamtx

  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
